"""
Voice profiles for VoiceGo - Indian voice conversion platform.
Each profile defines parameters for natural-sounding voice transformation.
"""

MALE_VOICES = [
    {
        "id": "arjun",
        "name": "Arjun",
        "gender": "male",
        "age": 20,
        "description": "Deep, confident college voice with a warm bass tone",
        "accent": "Hindi",
        "pitch_shift": -2.0,
        "formant_shift": 0.88,
        "speed": 0.98,
        "breathiness": 0.1,
        "roughness": 0.15,
        "color": "#4A90D9",
        "avatar_emoji": "👨‍🎓",
    },
    {
        "id": "rahul",
        "name": "Rahul",
        "gender": "male",
        "age": 19,
        "description": "Medium-pitched, friendly and approachable voice",
        "accent": "Hindi",
        "pitch_shift": -1.0,
        "formant_shift": 0.92,
        "speed": 1.0,
        "breathiness": 0.08,
        "roughness": 0.1,
        "color": "#5B8C5A",
        "avatar_emoji": "👦",
    },
    {
        "id": "vikram",
        "name": "Vikram",
        "gender": "male",
        "age": 22,
        "description": "Low, authoritative voice with rich bass undertones",
        "accent": "Punjabi",
        "pitch_shift": -4.0,
        "formant_shift": 0.85,
        "speed": 0.95,
        "breathiness": 0.05,
        "roughness": 0.2,
        "color": "#8B4513",
        "avatar_emoji": "🧔",
    },
    {
        "id": "rohan",
        "name": "Rohan",
        "gender": "male",
        "age": 18,
        "description": "Youthful, energetic teen voice with natural clarity",
        "accent": "Hindi",
        "pitch_shift": 0.5,
        "formant_shift": 0.95,
        "speed": 1.05,
        "breathiness": 0.12,
        "roughness": 0.05,
        "color": "#FF6B35",
        "avatar_emoji": "🧑",
    },
    {
        "id": "aditya",
        "name": "Aditya",
        "gender": "male",
        "age": 21,
        "description": "Smooth, charismatic voice perfect for narration",
        "accent": "Marathi",
        "pitch_shift": -1.5,
        "formant_shift": 0.90,
        "speed": 0.97,
        "breathiness": 0.15,
        "roughness": 0.08,
        "color": "#9B59B6",
        "avatar_emoji": "👨",
    },
    {
        "id": "karan",
        "name": "Karan",
        "gender": "male",
        "age": 20,
        "description": "Calm, soothing voice with gentle modulation",
        "accent": "Hindi",
        "pitch_shift": -0.5,
        "formant_shift": 0.93,
        "speed": 0.96,
        "breathiness": 0.18,
        "roughness": 0.05,
        "color": "#2ECC71",
        "avatar_emoji": "🙂",
    },
    {
        "id": "dev",
        "name": "Dev",
        "gender": "male",
        "age": 22,
        "description": "Husky, slightly raspy voice with character",
        "accent": "Bengali",
        "pitch_shift": -2.5,
        "formant_shift": 0.87,
        "speed": 0.98,
        "breathiness": 0.08,
        "roughness": 0.25,
        "color": "#E74C3C",
        "avatar_emoji": "😎",
    },
    {
        "id": "sahil",
        "name": "Sahil",
        "gender": "male",
        "age": 19,
        "description": "Soft-spoken, gentle voice with warmth",
        "accent": "Gujarati",
        "pitch_shift": 0.0,
        "formant_shift": 0.94,
        "speed": 0.94,
        "breathiness": 0.22,
        "roughness": 0.03,
        "color": "#3498DB",
        "avatar_emoji": "🤗",
    },
    {
        "id": "aarav",
        "name": "Aarav",
        "gender": "male",
        "age": 18,
        "description": "Bright, youthful teen voice full of energy",
        "accent": "Hindi",
        "pitch_shift": 1.0,
        "formant_shift": 0.96,
        "speed": 1.08,
        "breathiness": 0.1,
        "roughness": 0.05,
        "color": "#F39C12",
        "avatar_emoji": "🌟",
    },
    {
        "id": "nikhil",
        "name": "Nikhil",
        "gender": "male",
        "age": 21,
        "description": "Clear, articulate voice with perfect diction",
        "accent": "Tamil",
        "pitch_shift": -1.0,
        "formant_shift": 0.91,
        "speed": 1.0,
        "breathiness": 0.06,
        "roughness": 0.1,
        "color": "#1ABC9C",
        "avatar_emoji": "💪",
    },
]

FEMALE_VOICES = [
    {
        "id": "priya",
        "name": "Priya",
        "gender": "female",
        "age": 19,
        "description": "Sweet, melodious voice with a cheerful tone",
        "accent": "Hindi",
        "pitch_shift": 4.0,
        "formant_shift": 1.15,
        "speed": 1.02,
        "breathiness": 0.2,
        "roughness": 0.02,
        "color": "#FF69B4",
        "avatar_emoji": "👩‍🎓",
    },
    {
        "id": "ananya",
        "name": "Ananya",
        "gender": "female",
        "age": 20,
        "description": "Soft, gentle voice with a calming presence",
        "accent": "Hindi",
        "pitch_shift": 3.0,
        "formant_shift": 1.12,
        "speed": 0.97,
        "breathiness": 0.25,
        "roughness": 0.02,
        "color": "#DDA0DD",
        "avatar_emoji": "🧕",
    },
    {
        "id": "ishita",
        "name": "Ishita",
        "gender": "female",
        "age": 21,
        "description": "Clear, confident voice with natural authority",
        "accent": "Marathi",
        "pitch_shift": 2.5,
        "formant_shift": 1.10,
        "speed": 1.0,
        "breathiness": 0.12,
        "roughness": 0.05,
        "color": "#FF4500",
        "avatar_emoji": "👩",
    },
    {
        "id": "kavya",
        "name": "Kavya",
        "gender": "female",
        "age": 19,
        "description": "Melodious, musical voice perfect for singing",
        "accent": "Kannada",
        "pitch_shift": 5.0,
        "formant_shift": 1.18,
        "speed": 0.98,
        "breathiness": 0.18,
        "roughness": 0.01,
        "color": "#FF1493",
        "avatar_emoji": "🎤",
    },
    {
        "id": "neha",
        "name": "Neha",
        "gender": "female",
        "age": 22,
        "description": "Warm, nurturing voice with depth and emotion",
        "accent": "Hindi",
        "pitch_shift": 2.0,
        "formant_shift": 1.08,
        "speed": 0.96,
        "breathiness": 0.15,
        "roughness": 0.08,
        "color": "#C71585",
        "avatar_emoji": "💖",
    },
    {
        "id": "riya",
        "name": "Riya",
        "gender": "female",
        "age": 18,
        "description": "Youthful, bubbly teen voice full of life",
        "accent": "Hindi",
        "pitch_shift": 5.5,
        "formant_shift": 1.20,
        "speed": 1.08,
        "breathiness": 0.2,
        "roughness": 0.02,
        "color": "#FF6EB4",
        "avatar_emoji": "🌸",
    },
    {
        "id": "simran",
        "name": "Simran",
        "gender": "female",
        "age": 20,
        "description": "Expressive, dynamic voice with great range",
        "accent": "Punjabi",
        "pitch_shift": 3.5,
        "formant_shift": 1.14,
        "speed": 1.02,
        "breathiness": 0.14,
        "roughness": 0.04,
        "color": "#DB7093",
        "avatar_emoji": "✨",
    },
    {
        "id": "tanvi",
        "name": "Tanvi",
        "gender": "female",
        "age": 19,
        "description": "Gentle, whispery voice with an intimate feel",
        "accent": "Telugu",
        "pitch_shift": 3.0,
        "formant_shift": 1.13,
        "speed": 0.95,
        "breathiness": 0.30,
        "roughness": 0.01,
        "color": "#FFB6C1",
        "avatar_emoji": "🦋",
    },
    {
        "id": "diya",
        "name": "Diya",
        "gender": "female",
        "age": 18,
        "description": "Bright, sparkling voice with infectious energy",
        "accent": "Hindi",
        "pitch_shift": 4.5,
        "formant_shift": 1.16,
        "speed": 1.05,
        "breathiness": 0.16,
        "roughness": 0.03,
        "color": "#FFD700",
        "avatar_emoji": "🌻",
    },
    {
        "id": "meera",
        "name": "Meera",
        "gender": "female",
        "age": 21,
        "description": "Rich, deep female voice with sophistication",
        "accent": "Bengali",
        "pitch_shift": 1.5,
        "formant_shift": 1.06,
        "speed": 0.97,
        "breathiness": 0.10,
        "roughness": 0.06,
        "color": "#8B008B",
        "avatar_emoji": "🌹",
    },
]

ALL_VOICES = MALE_VOICES + FEMALE_VOICES


def get_voice_by_id(voice_id: str) -> dict | None:
    for voice in ALL_VOICES:
        if voice["id"] == voice_id:
            return voice
    return None
